services:
    php-apache:
        image: php:8.4.17-apache
        container_name: haikoshi-gongbing-editor
        ports:
            - 8888:80
        volumes:
            - ./upload/:/var/www/html:z
